StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5DDEFB516A0DA608}" {
   Id "ACE_Carrying-AddonName"
   Target_en_us "ACE - Carrying"
   Target_ko_kr "ACE - 업기"
   Modified 1578023399
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{5DDEFB51C773DDD9}" {
   Id "ACE_Carrying-UserAction_Carry"
   Target_en_us "Carry"
   Target_fr_fr "Porter"
   Target_de_de "Tragen"
   Target_cs_cz "Nést"
    Target_ko_kr "업기"
   Modified 1574895272
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{5E0C2A71118B03B7}" {
   Id "ACE_Carrying-UserAction_Carrying"
   Target_en_us "Carrying"
   Target_fr_fr "Porter"
   Target_de_de "Am Tragen"
   Target_cs_cz "Nošení"
    Target_ko_kr "업는 중"
   Modified 1577870149
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{5E0EB8A9BCC4201E}" {
   Id "ACE_Carrying-UserAction_Release"
   Target_en_us "Release"
   Target_fr_fr "Déposer"
   Target_de_de "Ablegen"
   Target_cs_cz "Položit"
    Target_ko_kr "놓기"
   Modified 1578028452
   Author "kexanone"
   LastChanged "Psycool"
  }
 }
}